#' Ingest pdf file of emails and create a list with required content
#'
#' Emails saved as a single pdf file are read into R as a list using this function. Only text that is
#' relevant for creating a data frame of variables "subject", "date", "to", "from", "content"
#' is selected to return the final desired list.
#'
#' @param pdfinput a pdf file of received emails
#'
#' @return a list containing the selected email data
#' @export
#'

pdfselect <- function(pdfinput) {

  # pdftools package needed to use pdf_text
  pdfdoc <- pdftools::pdf_text(pdfinput)
  # strsplit is a base R function so the package does not need to be called
  pdfdata <- strsplit(pdfdoc, "\n")
  # remove elements from the list generated by pdfformat function that don't have all four of Subject: Date: From: To: in that order
  keep <- grep("Subject:.*Date:.*From:.*To:", pdfdata)
  pdfdata <- pdfdata[keep]
}
